# Spring
spring:
  # DataSource
  datasource:
    url: jdbc:mysql://localhost:3306/fabryque?serverTimezone=Asia/Taipei
    username: root
    password: password
  # SessionFactory
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate: 
        dialetct: org.hibernate.dialect.MySQLDialect

# embedded container settings
server:
  # ContextPath
  servlet:
    context-path: /fabryque